receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:44317

exporters:
  otlp/2:
    endpoint: 0.0.0.0:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - otlp/2
